### ISSUE TITLE
[MIGRATED] Launch Readiness Checklist: Content

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1578]
To support a successful launch, content is king, starting with content seeded by MoFo staff and followed by locally-relevant content development ahead of launch. 

- [ ] In-house “starter” content seeded to show tool capabilities (#1574, #1575, #1576)
- [ ] Community platform features implemented (curation, moderation, featuring)
- [ ] > 48 projects in discovery gallery in local languages

cc @HPaulJohnson

**Comment by secretrobotron** [comment]
From content strategy meeting:
> more like 50 than 10

@thisandagain do you have a feel for how much content we need to make the system feel "full"? Would like to have a goal to aim for instead of "as much as possible".

**Comment by thisandagain** [comment]
Yup. Great question ... it's different on mobile than on desktop. In a 3-colum wide discovery view on desktop browsers you need about 48 items (16 rows) to feel "full". On mobile it's quite a bit easier and we could likely get away with about 20 items based on our current mockups for launch. I'd use that as a baseline ... anything we can do above and beyond will help.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/40"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/40.
Please don't comment on it here.
