### ISSUE TITLE
Launch Readiness Checklist: On-the-ground support

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1605]
In each target locale, have volunteer and paid resources that can help deploy marketing campaigns, lead localization and QA efforts and oversee ongoing development of locally-relevant content.

- [ ] 1 local Mozillian volunteer identified and training started
- [ ] 1 local marketing lead contracted and training started
- [ ] 1 localization and content development lead contracted and training

### DEADLINE: JUNE 1

cc @hpauljohnson

**Comment by xmatthewx** [comment]
@secretrobotron - is covered by granular issues in the launch repo?

**Comment by secretrobotron** [comment]
Yeah, this and the others can probably go away.
