### ISSUE TITLE
Launch Readiness Checklist: Product

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1606]
App-readiness to be determined in two phases: beta release of app and launch in Google Play. Readiness dependent on app localization and locale-specific Google Play deployment plan.

- [ ] Beta app available
- [ ] App localized in all first-wave markets
- [ ] QA complete on all localized version of app
- [ ] App launch plan for local versions of Google Play finalized

cc @HPaulJohnson

**Comment by secretrobotron** [comment]
Obsolete. Tracking progress in github.com/mozilla/webmaker-launch now.
