### ISSUE TITLE
Launch Readiness Checklist: Community

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1607]
Recognizing community is a key driver of in-market promotion, we need to train local community ahead of launch and supply them with appropriate promotional assets to deliver our key messages and CTA. 

- [ ] Community participation/promotional kit delivered
- [ ] Community training complete
- [ ] Collateral/swag delivered

cc @HPaulJohnson

**Comment by secretrobotron** [comment]
Obsolete. Tracking progress in github.com/mozilla/webmaker-launch now.
