### ISSUE TITLE
Launch Readiness Checklist: Partnerships

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1609]
Partnership outreach in many of these locations has been an ongoing efforts with current Webmaker beta and research efforts. The launch component will be pivoting to turn these partners into promotional agents around the launch to create buzz and to serve as an early distribution channel to lead users.  

- [ ] 2+ local partners secured
- [ ] Partnership participation/promotional kit delivered
- [ ] Partnership training complete

cc @HPaulJohnson

**Comment by secretrobotron** [comment]
@HPaulJohnson we should move these Launch Readiness issues to webmaker-launch.
#1605 #1606 #1607 #1608

**Comment by secretrobotron** [comment]
Obsolete. Tracking progress in github.com/mozilla/webmaker-launch now.
