### ISSUE TITLE
Alpha - Send APK w/ install notes to all MOFO

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1634]
- [x] Write up release notes and send APK to all MOFO
- [x] Write up installation guide
- [x] Include link to `nightly` release
- [x] Share install guide at weekly project meeting

**Comment by thisandagain** [comment]
Sent!
