### ISSUE TITLE
Rename repo & merge v1 into master / develop

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1712]
- [x] Rename repo to `webmaker-android`
- [x] Merge `v1` branch into `develop`
- [x] Make `develop` the default branch
- [x] Merge `develop` into master
- [ ] Update readme

**Comment by k88hudson** [comment]
:dancers:
