### ISSUE TITLE
[MIGRATED] Prep video, screenshots, and marketing copy for Google Play

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1838]
Related to #1836 

#### Launch Checklist
http://developer.android.com/distribute/tools/launch-checklist.html

#### Marketing Checklist
- [ ] Video (https://github.com/mozilla/webmaker-android/issues/1456)
- [x] Graphics
    - [x] High-resolution Icon (512 x 512 w/ transparency)
    - [x] Feature graphic (1024w x 500h w/ NO transparency)
    - [x] Promo graphic (180w x 120h w/ NO transparency)
- [ ] Screenshots
    - [x] Phone
    - [ ] 7-inch Tablet
    - [ ] 10-inch Tablet
- [x] Copy
    - [x] Title
    - [x] Short description (80 chars)
    - [x] Full description (4000 chars)

**Comment by secretrobotron** [comment]
:+1: thanks.
Working with the MoCo creative team for a video by June 5.
Would be super useful to have screenshots and language for them well before then too.

**Comment by thisandagain** [comment]
Updated the list of required assets as per Google Play. See above.

/cc @hpauljohnson @vazquez

**Comment by vazquez** [comment]
@thisandagain - Do we need the TV Banner asset? It seems that the app's banner asset would only be displayed on Android TV devices.

**Comment by vazquez** [comment]
@thisandagain @hpauljohnson - What screenshot of the app are we thinking of going with?

**Comment by vazquez** [comment]
@thisandagain @hpauljohnson - Another question, do we want to go for normal screenshots, or do we want to design something akin to Messenger? https://play.google.com/store/apps/details?id=com.facebook.orca

**Comment by thisandagain** [comment]
@vazquez 

Re: TV. Good catch ... copypasta.
Re: Screenshot. We can use multiple ... I recommend we choose a variety. For the "hero" shot I'd recommend either discover or the project view.
Re: Style. I've tried both over the last couple years ... IME inset with description tagline generally converts better.

**Comment by xmatthewx** [comment]
@vazquez - Screenshots can hit these messages: 
 - Create
 - Discover
 - Share
 - Local
 - Free & Open Source

For Share, can we show Android's sharing sheet? A curated list of logos would add some legitimacy.  

Let's keep this fairly simple. We'll A/B test and iterate as we learn more.

**Comment by xmatthewx** [comment]
Launch checklist includes links to these two resources re: graphic assets:
 - http://android-developers.blogspot.com/2011/10/android-market-featured-image.html
 - https://support.google.com/googleplay/android-developer/answer/1078870

**Comment by xmatthewx** [comment]
@hpauljohnson @KevZawacki - we need copy to go with the screenshots for the play store. Character count and a few mediocre ideas here: https://etherpad.mozilla.org/play-store-copy

WIP designs for reference:
![screenshot 2015-06-04 13 34 21](https://cloud.githubusercontent.com/assets/53411/7990364/95f0ea16-0abe-11e5-92bf-69be2f6c99d7.png)


p.s. github refuses to autocomplete @hpauljohnson's handle. making me :banana::banana::banana:s

**Comment by vazquez** [comment]
the autocomplete happens to me too with Paul :alien:

**Comment by HPaulJohnson** [comment]
@kevZawacki and I will finalize this afternoon, put it in the etherpad above and let you know when it's ready. 

re: autocomplete issues i suggest you log all complaints here: https://github.com/mozilla/webmaker-launch/issues/11

**Comment by KevZawacki** [comment]
@xmatthewx: @HPaulJohnson and I drafted Play Store copy, now in your etherpad.

https://etherpad.mozilla.org/play-store-copy

**Comment by vazquez** [comment]
@KevZawacki - Thanks Kevin. All are looking good, except for Local. It is far too long; it also doesn't fit the action verb first pattern that we're using in the other screenshots (ie. Discover, Create, Share)

**Comment by vazquez** [comment]
@KevZawacki - What about this?

![screenshot 2015-06-04 17 15 48](https://cloud.githubusercontent.com/assets/1119821/7994696/6d19af14-0add-11e5-9a77-f2186dc24dd1.png)

**Comment by thisandagain** [comment]
Looking great @vazquez ! Couple nitpicks:
- I'd like to stick with our standard palette (perhaps teal, blue, and plum?). These colors are starting to venture into Google territory.
- The Android share intent forces the status bar to black

**Comment by vazquez** [comment]
@thisandagain -

- **Re: Android share** - great catch :+1: 
- **Re: Colours.** I'd like to offer a rationale to see if I can sway you the opposite direction. I initially tried our primary interface colours. 
 - Plum is far too serious for a background colour. 
 - Teal doesn't have enough contrast. 
 - The Blue background looks weird with a primarily blue interface (ie. blue on blue). I chose to go to with the default colours that we present in element attributes:
  ![screenshot 2015-06-04 17 31 56](https://cloud.githubusercontent.com/assets/1119821/7995004/160ca8b8-0ae0-11e5-9201-af302b15db00.png)
  - The colours evoke a playful quality, which is in line with the goal of the app. Using the interface colours for marketing purposes turned the app into something serious.

All in all, maybe iterating these colours to increase the saturation so that it doesn't look googley?

**Comment by thisandagain** [comment]
I think the yellow, red, and green in particular (regardless of the saturation) feel like insta-Google. Happy to play with the teal and blue to work a little better though (increase saturation and bring down the lightness a bit?). Plum as too serious ... yeah, you might be right about that. The purple from the tinker mode button might be interesting to look at though.

**Comment by vazquez** [comment]
@thisandagain - Okay, what about this?

![screenshot 2015-06-04 17 59 01](https://cloud.githubusercontent.com/assets/1119821/7995400/6f9b701e-0ae3-11e5-82a1-8727e7d6ed92.png)

**Comment by thisandagain** [comment]
Ooooh yeah! :wink:

**Comment by vazquez** [comment]
:dancer:

**Comment by KevZawacki** [comment]
@vazquez +1 to 'Experience a Web in your language & community.' Thanks for the improvement!

**Comment by xmatthewx** [comment]
Nearly done. Assets should easily be ready Monday. Bumping to 3/2 milestone to wrap it up.

**Comment by vazquez** [comment]
#### Device Screenshots

Adjusted the colours and assets.  

![discover screenshot_1](https://cloud.githubusercontent.com/assets/1119821/8009814/477e633e-0b79-11e5-9216-521e7e1a037e.png)

![create screenshot](https://cloud.githubusercontent.com/assets/1119821/8009340/3acb73f0-0b76-11e5-9624-c9f0574e0d1f.png)  

![share screenshot_1](https://cloud.githubusercontent.com/assets/1119821/8009996/92d68f5e-0b7a-11e5-9df9-f6947afe83ae.png)


![local screenshot_1](https://cloud.githubusercontent.com/assets/1119821/8009973/70b95348-0b7a-11e5-8f21-e784559d9fec.png)



![free and open source screenshot_1](https://cloud.githubusercontent.com/assets/1119821/8009697/8dea4410-0b78-11e5-9b78-7802fb301bab.png)

**Comment by vazquez** [comment]
Note: Github is interpreting the colours a bit different than what they actually are. The teal and red are more vibrant.

**Comment by vazquez** [comment]
#### Feature graphic

I chose to go with some simple, especially since the wordmark will change.

![feature graphic copy](https://cloud.githubusercontent.com/assets/1119821/8010113/7aff31dc-0b7b-11e5-8a71-763525ee3858.png)

We can add the "Connect the things you love" tagline underneath the wordmark, how does everybody feel about that?

**Comment by HPaulJohnson** [comment]
I'd like to propose an alternate tagline. "Connect..." didn't test that well (on Facebook at least). When do we need to have this finalized?

**Comment by thisandagain** [comment]
Thursday next week (11th).

**Comment by KevZawacki** [comment]
Can we go with "Create. Discover. Share."?

**Comment by vazquez** [comment]
@thisandagain Assets are available here: https://drive.google.com/a/mozilla.com/folderview?id=0ByIoeeW0a3R_U2cyNVcwakpqcWc&usp=sharing

**Comment by edrushka** [comment]
cc @lovegushwa these would be great for posters

**Comment by thisandagain** [comment]
@vazquez I just need the tablet sizes and then I think we can close this out! (Next week is fine)

**Comment by vazquez** [comment]
@thisandagain - Gutcheck: would this be okay?

![artboard 46](https://cloud.githubusercontent.com/assets/1119821/8142495/1e4fe810-114c-11e5-8e2c-45e7f627c40d.png)

**Comment by edrushka** [comment]
Hey @vazquez I downloaded the app and noticed there's a period missing after "share" on the install screen top banner. https://www.evernote.com/shard/s384/sh/4dbe8b92-9004-473c-addd-d95f73ddd5e8/0b1d732a1294ce821b306974ca91e043

**Comment by vazquez** [comment]
@edrushka Thanks so much for bring it to my attention! I'm re-exporting the asset right now.

**Comment by vazquez** [comment]
@thisandagain The Feature and Promo Graphic with the period are here: https://drive.google.com/a/mozilla.com/folderview?id=0ByIoeeW0a3R_U2cyNVcwakpqcWc&usp=sharing

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/112"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/112.
Please don't comment on it here.
