### ISSUE TITLE
[MIGRATED] Meta: Improve overall experience of error and loading states

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2258]
There are some follow-up tickets to **improve UI around error and loading states**:

* [ ] Page/project loading states: https://github.com/mozilla/webmaker-android/issues/1680
* [ ] Image loading: https://github.com/mozilla/webmaker-android/issues/1783
* [ ] Technical refactoring: https://github.com/mozilla/webmaker-android/issues/1946

(feel free to add others I have missed)

Before implementing these, I think we should ask design to look at the current implementations for different types of errors, and re-evaluate solutions from an overall perspective, perhaps taking into account actual user feedback.

**Comment by Pomax** [comment]
left a comment on https://github.com/mozilla/webmaker-android/issues/1680 regarding the load screen experience

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/200"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/200.
Please don't comment on it here.
