### ISSUE TITLE
Tracking - get new one-password style login working with CORS, mobile

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#447]
Some blocking bugs include:
- [x] enable mobile testing/viewports webmaker-login-ux https://github.com/mozilla/webmaker-login-ux/commit/efa88de703d42af323d48e20153e8717654b27ae
- [x] adjust mobile UI/UX to work for mobile screens https://github.com/mozilla/webmaker-login-ux/issues/44
- [x] implement CORS on all routes
- [x] integrate ui in webmaker-app https://github.com/mozillafordevelopment/webmaker-app/issues/463
- [x] make webmaker-login-ux work with browserify https://github.com/mozilla/webmaker-login-ux/issues/55

We will also need UX/implementation of SMS-based one-time passwords, as well as the optional creation of passwords. I expect that email-only one-time passwords will be insufficient for our user experience.

I will add bugs as they are filed
